= Dockerの紹介

Dockerはコンテナ型の仮想環境を構築するための軽量なプラットフォームです。 +
2013年3月に登場し、一気に注目を集めました。その後GoogleやMicrosoftなどの企業もDockerを採用しています。 +

== 特徴

Dockerの特徴の最大のポイントは *コンテナ型仮想化技術* です。 +
コンテナとは独立した仮想的な空間です。 +
複数のコンテナを同時に立てて動作させることもできますが、通常は別のコンテナへはアクセスできないようになっています。 +

コンテナはアプリケーションを起動するために必要なライブラリやアプリケーション本体を含み、1コンテナにつき1プロセスを実行させるのが慣例となっています。 +
コンテナ型の仮想化では同一ホストOS上でコンテナエンジンが起動し、これが各コンテナの管理を行います。

PCは通常、あるソフトウェアの最新バージョンと過去バージョンを共存し動作させることは不可能ですが +
Dockerを使用すると各コンテナは独立した状態で動作するのでホストOSが動作している1台のPC上でバージョン違いのソフトウェアを同時に動作させることも可能になります。

== メリット

ここではDockerの特徴に由来するメリットについて説明します。 +

=== 環境構築が簡単

DockerはDocker Hubというコンテナイメージを配布しているサイトがあるため必要な環境に近いイメージをダウンロードし、少し変更を加えることで望んだ環境を準備することができます。

=== 環境を共有できる

DockerがインストールされているPCさえあれば、同じDockerイメージを使用しコンテナを作成するだけで環境を共有することができます。 +
従来まで環境構築といえば、手順書に従って必要なソフトウェアをインストールしたりパスを通したりなど作業内容が多かったのですが、そういったものが不要になります。 +
DockerfileやDocker-compose.yamlというファイルがありますが、これらが環境構築手順書となっていてそれを元にDockerが環境を作成してくれます。 +

また、開発環境と本番環境で同様のコンテナを使用すれば *環境差異が極めて小さくなるため* ソフトウェアのバージョン違いなどから起こる不具合などを防ぐことができます。

=== リソース消費が少ない

仮想環境と聞いてVirtualBoxなどを思い浮かべる人もいるかと思います。 +
従来の仮想環境であるハイパーバイザー型の仮想環境は仮想マシン上でゲストOSを動作させていたためリソースの消費が大きかったのです。 +

Dockerはコンテナ型という仮想化技術であり、コンテナ型はアプリケーションの実行のみを担うためハイパーバイザー型から比べてリソースの消費が少なくなります。

== 参考ページ

https://agency-star.co.jp/column/docker/